In [3]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC


In [4]:
from sklearn import svm
from sklearn.svm import SVC

In [5]:
train_data = pd.read_csv("archive\MNIST\mnist_train.csv") #reading the csv files using pandas
test_data = pd.read_csv("archive\MNIST\mnist_test.csv")

In [6]:
df = train_data

df.describe()

label      1x1      1x2      1x3      1x4      1x5      1x6  \
count  60000.000000  60000.0  60000.0  60000.0  60000.0  60000.0  60000.0   
mean       4.453933      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.889270      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

           1x7      1x8      1x9  ...         28x19         28x20  \
count  60000.0  60000.0  60000.0  ...  60000.000000  60000.000000   
mean       0.0      0.0      0.0  ...      0.200433      0.088867   
std        0.0      0.0      0.0  ...      6.042472      3.956189   
min        0.0      0.0      0.0  ...      0.000000      0.000000   
25%        0.0      0.0      0.0  ...      0.000000      0.000000   
50%        0.0      0.0      0.0  ...      0.000000      0.000000   
75%        0.0      0.0      0.0  ...      0.000000      0.000000   
max        0.0      0.0      0.0  ...    254.000000    254.000000   

              28x21         28x22         28x23       28x24    28x25    28x26  \
count  60000.000000  60000.000000  60000.000000  60000.0000  60000.0  60000.0   
mean       0.045633      0.019283      0.015117      0.0020      0.0      0.0   
std        2.839845      1.686770      1.678283      0.3466      0.0      0.0   
min        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
25%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
50%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
75%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
max      253.000000    253.000000    254.000000     62.0000      0.0      0.0   

         28x27    28x28  
count  60000.0  60000.0  
mean       0.0      0.0  
std        0.0      0.0  
min        0.0      0.0  
25%        0.0      0.0  
50%        0.0      0.0  
75%        0.0      0.0  
max        0.0      0.0  

[8 rows x 785 columns]

In [8]:
df.shape

(60000, 785)

In [9]:
df.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [10]:
df.isnull().sum()

label    0
1x1      0
1x2      0
1x3      0
1x4      0
        ..
28x24    0
28x25    0
28x26    0
28x27    0
28x28    0
Length: 785, dtype: int64

In [11]:
df.columns

Index(['label', '1x1', '1x2', '1x3', '1x4', '1x5', '1x6', '1x7', '1x8', '1x9',
       ...
       '28x19', '28x20', '28x21', '28x22', '28x23', '28x24', '28x25', '28x26',
       '28x27', '28x28'],
      dtype='object', length=785)

In [12]:
order = list(np.sort(df['label'].unique()))
print(order)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [13]:


y = train_data['label']

X = train_data.drop(columns = 'label')

print(train_data.shape)

(60000, 785)


In [14]:
## Normalization

X = X/255.0
test_data = test_data/255.0

print("X:", X.shape)
print("test_data:", test_data.shape)

X: (60000, 784)
test_data: (10000, 785)


In [15]:
from sklearn.preprocessing import scale
X_scaled = scale(X)

# train test split
x_train, x_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.3, train_size = 0.2 ,random_state = 10)

In [17]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


In [18]:
linearSVM = svm.SVC(kernel='linear')
polynomialSVM = svm.SVC(kernel='poly', degree=3)  
rbfSVM = svm.SVC(kernel='rbf')
sigmoidSVM = svm.SVC(kernel='sigmoid')

In [26]:
linearSVM.fit(x_train,y_train)
linear_predictions = linearSVM.predict(x_test)



In [27]:
polynomialSVM.fit(x_train,y_train)
poly_predictions = polynomialSVM.predict(x_test)

In [28]:
rbfSVM.fit(x_train,y_train)
rbf_predictions = rbfSVM.predict(x_test)


In [29]:
sigmoidSVM.fit(x_train,y_train)
sigmoid_predictions = sigmoidSVM.predict(x_test)

In [30]:

linear_accuracy = accuracy_score(y_test, linear_predictions)
poly_accuracy = accuracy_score(y_test, poly_predictions)
rbf_accuracy = accuracy_score(y_test, rbf_predictions)
sigmoid_accuracy = accuracy_score(y_test, sigmoid_predictions)

print("Linear SVM Accuracy:", linear_accuracy)
print("Polynomial SVM Accuracy:", poly_accuracy)
print("RBF SVM Accuracy:", rbf_accuracy)
print("Sigmoid SVM Accuracy:", sigmoid_accuracy)

Linear SVM Accuracy: 0.9103333333333333
Polynomial SVM Accuracy: 0.9132222222222223
RBF SVM Accuracy: 0.943
Sigmoid SVM Accuracy: 0.9010555555555556


In [34]:
from sklearn import metrics

print("\nConfusion matrix for linear kernel\n" )
print(metrics.confusion_matrix(y_true=y_test, y_pred=linear_predictions))
print("\nConfusion matrix for poly kernel\n" )
print(metrics.confusion_matrix(y_true=y_test, y_pred=poly_predictions))
print("\nConfusion matrix for rbf kernel\n" )
print(metrics.confusion_matrix(y_true=y_test, y_pred=rbf_predictions))
print("\nConfusion matrix for sigmoid kernel\n" )
print(metrics.confusion_matrix(y_true=y_test, y_pred=sigmoid_predictions))


Confusion matrix for linear kernel

[[1719    0   10    5    3   16   12    1    6    0]
 [   1 1951   11    5    5    4    0    3   11    1]
 [  11   26 1676   30   23    5   23   19   17    1]
 [  10    4   47 1627    4   66    5   19   42   10]
 [   4    8   21    1 1658    5   14    6    5   50]
 [  21    9   19   87   12 1423   30    1   39   11]
 [  20    7   23    1   14   20 1666    2    4    0]
 [   7   13   19   16   31    4    2 1774    5   93]
 [  25   44   49   54   12   58   18   11 1436   17]
 [   4   11   19   23   90    9    1   69   20 1456]]

Confusion matrix for poly kernel

[[1649    0    7    2    8    9   11    1   84    1]
 [   0 1941    8    5    6    0    2    1   28    1]
 [   4    8 1576   15   53    2    5    7  159    2]
 [   1    2   15 1644    6   24    0   11  113   18]
 [   0    5   14    0 1685    3    4    0    5   56]
 [   2    1    1   33   27 1388   18    2  149   31]
 [   3    4    3    0   26   14 1657    0   50    0]
 [   1   14    5    1   76

TRAINING ACCURACIES

In [48]:
svm_linear_model = svm.SVC(kernel='linear')
svm_linear_model.fit(x_train, y_train)

train_predictions_linear = svm_linear_model.predict(x_train)
train_accuracy_linear = accuracy_score(y_train, train_predictions_linear)
print("Training Accuracy (Linear Kernel):", train_accuracy_linear)

Training Accuracy (Linear Kernel): 1.0


In [49]:
svm_poly_model = svm.SVC(kernel='poly')
svm_poly_model.fit(x_train, y_train)

train_predictions_poly = svm_poly_model.predict(x_train)
train_accuracy_poly = accuracy_score(y_train, train_predictions_poly)
print("Training Accuracy (poly Kernel):", train_accuracy_poly)

Training Accuracy (poly Kernel): 0.95025


In [50]:
svm_rbf_model = svm.SVC(kernel='rbf')
svm_rbf_model.fit(x_train, y_train)

train_predictions_rbf = svm_rbf_model.predict(x_train)
train_accuracy_rbf = accuracy_score(y_train, train_predictions_rbf)
print("Training Accuracy (rbf Kernel):", train_accuracy_rbf)

Training Accuracy (rbf Kernel): 0.98075


In [44]:
svm_sigmoid_model = svm.SVC(kernel='sigmoid')
svm_sigmoid_model.fit(x_train, y_train)

train_predictions_sigmoid = svm_sigmoid_model.predict(x_train)
train_accuracy_sigmoid = accuracy_score(y_train, train_predictions_sigmoid)
print("Training Accuracy (sigmoid Kernel):", train_accuracy_sigmoid)

Training Accuracy (sigmoid Kernel): 0.9099166666666667


In [47]:
print("SVM model accuracies for different kernels\n")


print("Training accuracis:")
print("\n\t\tLinear kerenel: ",train_accuracy_linear)
print("\n\t\tpolynomial kerenel: ",train_accuracy_poly)
print("\n\t\trbf kerenel: ",train_accuracy_rbf)
print("\n\t\tSigmoid kerenel: ",train_accuracy_sigmoid)


print("\n\nTesting accuracis:")
print("\n\t\tLinear kerenel: ",linear_accuracy)
print("\n\t\tpolynomial kerenel: ",poly_accuracy)
print("\n\t\trbf kerenel: ",rbf_accuracy)
print("\n\t\tSigmoid kerenel: ",sigmoid_accuracy)



SVM model accuracies for different kernels

Training accuracis:

		Linear kerenel:  1.0

		polynomial kerenel:  0.95025

		rbf kerenel:  0.98075

		Sigmoid kerenel:  0.9099166666666667


Testing accuracis:

		Linear kerenel:  0.9103333333333333

		polynomial kerenel:  0.9132222222222223

		rbf kerenel:  0.943

		Sigmoid kerenel:  0.9010555555555556


All kernels of SVM models produce a good accuracy.